export const sampleItems = [
  { name: "Apple" },
  { name: "Apricot" },
  { name: "Avocado" },
  { name: "Banana" },
  { name: "Blackberry" },
  { name: "Blueberry" },
  { name: "Cherry" },
  { name: "Clementine" },
  { name: "Cranberry" },
  { name: "Date" },
  { name: "Dragonfruit" },
  { name: "Durian" },
  { name: "Elderberry" },
  { name: "Fig" },
  { name: "Grape" },
  { name: "Grapefruit" },
  { name: "Guava" },
  { name: "Honeydew" },
  { name: "Jackfruit" },
  { name: "Kiwi" },
  { name: "Lemon" },
  { name: "Lime" },
  { name: "Lychee" },
  { name: "Mango" },
  { name: "Melon" },
  { name: "Nectarine" },
  { name: "Orange" },
  { name: "Papaya" },
  { name: "Peach" },
  { name: "Pear" },
  { name: "Pineapple" },
  { name: "Plum" },
  { name: "Pomegranate" },
  { name: "Quince" },
  { name: "Raspberry" },
  { name: "Strawberry" },
  { name: "Tangerine" },
  { name: "Tomato" },
  { name: "Ugli fruit" },
  { name: "Watermelon" },
  { name: "Xigua" },
  { name: "Yuzu" },
  { name: "Zucchini" },
  { name: "#123 Banana" },
  { name: "456 Apple" },
  { name: "#789 Mango" },
  { name: "$$$" },
  { name: "Vermillion" },
];
